name: bmi_calculator
description: A new Flutter project.

version: 1.0.2+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_responsive_screen: ^1.0.0
  font_awesome_flutter: ^8.5.0
  animated_text_kit: ^1.3.1
  dynamic_theme: ^1.0.1
  shared_preferences: ^0.5.3+4
  drawerbehavior: ^0.0.8
  share: ^0.6.2+1
  launch_review: ^2.0.0
  url_launcher: ^5.1.4
  get_version: ^0.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutterAlignmentGeometry

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  image_path: "Assets/Images/ic_launcher.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - Assets/Images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: Assets/fonts/GoogleSansRegular.ttf
